### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by alexsourcerer**
Just downloaded Corebird, saw english words, wanted to help, translated missing strings, done :)
hope it's all good :)

### CODE REVIEW

**Comment by baedert** [comment]
We handle translations using transifex, if I merge this now it will just get overridden at the next release. https://www.transifex.com/corebird/corebird/dashboard/

**Comment by alexsourcerer** [comment]
Does it mean i've done this for nothing of there's a way to "import" the work to transifex?

**Comment by baedert** [comment]
I don't really know how transifex works, I'm not a translator myself, sorry.

**Comment by Vistaus** [comment]
You can upload your po file using the Upload file button on Transifex as you can see in my screenshot:

screenshot_2016-08-01_17-03-18
(it says Dutch as that's my team, but it looks and works the same for the French team)

**Comment by baedert** [comment]
Thanks for the information, @Vistaus!

**Comment by Vistaus** [comment]
You're welcome! :smile:

**Pull request closed without merging**
