### PR TITLE
Implementation of Trending Topics · Issue #380 

### PR DESCRIPTION
**Pull request by contraultra**
corebird2

One caveat is that the user's trending topic location preference is not saved across launches
i.e. The user has to pick his/her trending topic location whenever he/she reopens corebird
Proposed Fix: Store the user's trending topic location preference in the database

Happy Holidays!

RE: [Feature request: Trending Topics · Issue #380 ](https://github.com/baedert/corebird/issues/380)

### CODE REVIEW

**Comment by baedert** [comment]
Why are the woeids saved on a per-account basis? The setting yes (I mean, I guess, I don't know why anyone would want diffrerent locations for different accounts that belong to the same person...), but just the string->woeid map looks like it belongs into the search page.

**Comment by contraultra** [comment]
The fetched JSON Array of Twitter's locations with trends is parsed by `set_locations_with_trends ()` where the `woeid_with_trends` map is created as per other JSON Responses received by `set_disabled_rts ()`,  `set_blocked ()` and `set_muted ()` in Account.vala

Do you want the JSON array to be set as an Account property that is then parsed by SearchPage.vala?

Does seem like a good idea as per separation of concerns...

**Comment by baedert** [comment]
Dunno, it seemed natural to me to *not* make it a property of Account since it doesn't depend on the account in any way (and Account already manages a lot :/). A setting for the trending location would probably go into the SettingsWindow instead of the account settings. Also please keep an eye on the indentation used; some of the changes seem to use tabs, some spaces, etc.

**Comment by contraultra** [comment]
I implemented this in `SearchPage.vala` since `Settings.vala` does not inherit `Account`... Fetching trends/locations and trends/available require authentication credentials from `Account.vala`. What would you do? I worked with what was present. :hushed:

**Comment by ricardoborgesjr** [comment]
Hello!
Firstly apologies for my bad English.
I am working also in a trending topics implementation.
My implementation is a bit different of its.
The Location setup is in the settings window
2016-01-28-221927_676x303_scrot
captura de tela de 2016-01-22 22-45-08

If "Show top tweet" setup is selected, show the most popular tweet about the trend topic, giving some 
"overview" about the topic.
captura de tela de 2016-01-22 22-45-26

Otherwise show only the trending topics, saving up some search request :).
captura de tela de 2016-01-27 18-44-54

I believe this week or next will be ready.
Case have some feedback, or just say "Come on, man! is this a bad idea" tell me :).

Code on: https://github.com/ricardoborgesjr/corebird/commits/trending-topics

Thanks in advance!

**Comment by contraultra** [comment]
Looks great to me! 😀

**Comment by IvanTurgenev** [comment]
Ok why theres still not trending topics?

**Comment by Vistaus** [comment]
@IvanTurgenev Because Twitter removed the old Trending Topics feature and integrated it with search and I'm not sure if they created an API for that. But even if there's an API, it's moot now anyway because Trending Topics requires constant polling which is, AFAIK, part of the streaming feature, which is about to be discontinued by Twitter.

**Comment by IvanTurgenev** [comment]
Should we come up with a solution? or are all twitter cliente going to die

**Pull request closed without merging**
