### PR TITLE
Fix Bug636 sigsegv after quoting

### PR DESCRIPTION
**Pull request by IBBoard**
Unit test and fix for SIGSEGV issue after quoting a tweet (bug #636). I'm not sure if it is perfect C code, but it makes the test pass and seems to stop Corebird crashing after I applied it.

### CODE REVIEW

**Comment by baedert** [comment]
I see what the problem is but I'd much rather eliminate the *only* place where `cb_mini_tweet_copy` is even needed, i.e. the coalesce operator at https://github.com/baedert/corebird/blob/master/src/async/ComposeJob.vala#L126 and replace it with a `Cb.MiniTweet*` pointer and an explicit null-check (since otherwise the coalesce operator won't work...).

**Comment by IBBoard** [comment]
But what if there's some extra code in future that does a copy? Wouldn't the bug come back?

As I said, I'm not a C person and I'm not used to memory managing, but unless the `cb_mini_tweet_free` function is also removed then wouldn't there still be a mismatch between how things are allocated on copy and how they're deallocated on free?

**Comment by baedert** [comment]
> But what if there's some extra code in future that does a copy? Wouldn't the bug come back?

If `cb_mini_tweet_copy` doesn't exist, the bug can't come back. That function really only exists because valac wanted it for the coalesce operator. A `CbMiniTweet` only ever belongs to one `CbTweet` and the latter is what we will actually work on and that's why it's a real `GObject`.

> As I said, I'm not a C person and I'm not used to memory managing, but unless the cb_mini_tweet_free function is also removed then wouldn't there still be a mismatch between how things are allocated on copy and how they're deallocated on free?

There can't be a difference between copy and free if copy doesn't exist. As long as free is fine it's ok.

**Comment by IBBoard** [comment]
Ah, so valac will complain and refuse to get into this situation if a copy function doesn't exist and we try to do something in future that it would compile down to a copy/free? I didn't know that. I'd assumed copying and freeing were linked in some way.

I'll try to write an alternate fix with pointers in Vala. I can't think how to write a test case for it, though, which feels wrong. Although if we're never copying then we'll only ever free when we dispose of that tweet, so maybe there explicitly isn't anything to test.

Also, does it need a null check? Given that Vala is enforcing the "non-null" behaviour now then the `source_tweet` can't be null, and if we do a null check then we'd have to raise an error (because we managed to get a quoted tweet but without a mini-tweet struct inside it). Is it better to do an `assert()` because we're basically guaranteed that it's not null and if it is then fundamental things have broken?

**Comment by IBBoard** [comment]
Actually, from quickly trying to code this, can we do it without the copy function?

If I remove the copy then I get the following when running `make check`:

```
…/tests/tweetmodel.vala:201: undefined reference to `cb_mini_tweet_copy'
…/tests/tweetmodel.vala:201: undefined reference to `cb_mini_tweet_copy'
…/tests/tweetmodel.vala:201: undefined reference to `cb_mini_tweet_copy'
```

(Why it complains about that assignment and not the earlier one, I don't know)

Looking up about structs in the docs, it says they're [copied on assignment in Vala](https://wiki.gnome.org/Projects/Vala/Tutorial#Structs). I've tried a bit of playing with Vala pointers in the test, but I can't something that compiles.

**Comment by baedert** [comment]
> Also, does it need a null check? Given that Vala is enforcing the "non-null" behaviour now then the source_tweet can't be null, and if we do a null check then we'd have to raise an error (because we managed to get a quoted tweet but without a mini-tweet struct inside it). Is it better to do an assert() because we're basically guaranteed that it's not null and if it is then fundamental things have broken?

I don't understand what you mean here. null check for what? source_tweet can never be null, it's not a pointer.

The failures in tweetmodel.vala can definitely be worked around, valac is just `cb_mini_tweet_init`'ing a new tweet and then directly copying it... I'd have to look up how to do that right now though.

**Comment by IBBoard** [comment]
Sorry, I think I misunderstood when you said:

> replace it with a Cb.MiniTweet* pointer and an explicit null-check (since otherwise the coalesce operator won't work...).

I was trying to check that the pointer didn't end up null, but as you said (and as I suspected) source_tweet can't be null and so it'll never happen. It just becomes an "if RT not null then pointer to RT else pointer to source" (although that seems to give compiler warnings about pointer types).

I've got the main part of the code fixed, but as I don't know the Vala to work around the init/copy then I can't provide an alternate patch for this issue that doesn't break building the tests.

**Comment by baedert** [comment]
Ok looks like removing the manual copy impl is fine but that code in the test cases can't be written without needing *some* copy implementation, so one solution would be adding `[CCode (has_copy_function= false)]` to `Cb.MiniTweet`. But that will just cause valac to write its own copy implementation for the test cases. So since there's no real way around it, I think the initial patch fixing `cb_mini_tweet_copy` is fine, but a test case for it seems silly.

**Comment by IBBoard** [comment]
It's up to you. I put the test case in so that a) I could get a failing test and then know that I'd fixed it and so that b) it would be obvious if something was changed in future and it broke. It seemed like the purpose of a unit test, and it doesn't take long to run at all.

**Comment by baedert** [comment]
Merged as cf37fa04bd5233d4d992adcb3aa1c4e6cd1ce15f

**Pull request closed without merging**
