### PR TITLE
Use CSS named colour (available in Adwaita and High Contrast) to make…

### PR DESCRIPTION
**Pull request by IBBoard**
… colouring match theme

Fix for #463

### CODE REVIEW

**Comment by baedert** [comment]
And now you depend on those being defined. I'm not using any variables from themes for a reason. they are not documented and not API. If themes decide to style things in corebird themselves, fine, if users change it, fine. It'll take about 5 days until the first bug about a missing color variable shows up.

**Comment by IBBoard** [comment]
Which is why I checked for them in Adwaita and High Contrast - the two Gnome themes. I'll see if there is a way to do fall-back.

**Comment by IBBoard** [comment]
I've been working on GTK theming and noticed these relevant bits in Adwaita:

    // apps rely on some named colors to be exported
https://github.com/GNOME/gtk/blob/gtk-3-16/gtk/theme/Adwaita/_colors-public.scss#L1

    @define-color theme_selected_bg_color #{"" +$selected_bg_color};
https://github.com/GNOME/gtk/blob/gtk-3-16/gtk/theme/Adwaita/_colors-public.scss#L26

So the "@theme_selected_bg_color" that I use is one that is intentionally exported. People rely on other exported colours (e.g. in Metacity themes) so I don't think it should be a problem to rely on a colour that is exported by Adwaita explicitly for the purpose of being used by apps.

**Comment by Vistaus** [comment]
Bug #463 got closed on Feb 18 due to this commit: https://github.com/baedert/corebird/commit/589aef76e90fe5ac5256f329b75b789e8086971d

Ss this PR still needed then?

**Comment by IBBoard** [comment]
Probably not. I still use the colours in my custom build (because the images are effectively hyperlinked, and themes have hyperlink colours, so we can show the colour), but since the bug is closed then this can go.

**Pull request closed without merging**
