### PR TITLE
(feat) added spell check for tweet compose text box.

### PR DESCRIPTION
**Pull request by sunng87**
This patch added spell check support for tweet composer to address #283 

I have added gtkspell3 as a dependency.

### CODE REVIEW

**Comment by baedert** [comment]
Without having it actually tried at all...

- There are \` missing around the package name in the `README.md`
- Indentation of the package line in the `configure.ac` is wrong
- Why is there a `spell_checker` in `ComposeWindow` now? It doesn't seem to be used at all.
- General coding style: space required before parentheses
- I would like a --disable-spell-check (so it's enabled by default) conifgure-time switch for this (that will turn off the dependency as well as all usages of any gtkspell API)

**Comment by sunng87** [comment]
@baedert Thanks for reviewing! I just made a force update to fix 1, 2 and 4.

I didn't see a `spell_checker` in `ComposeWindow`, did I miss something?

I will add a disable flag later today.

**Comment by baedert** [comment]
Woops, I meant `CompletionTextView`, sorry.

**Comment by sunng87** [comment]
@baedert compiler option added.

**Comment by sunng87** [comment]
@baedert possible to check again? Thanks!

**Comment by baedert** [comment]
I haven't forgot about it, no worries :p I'll be pretty busy until wednesday and look into it shirtly afterwards.

**Comment by sunng87** [comment]
Thanks for merging!

**Comment by baedert** [comment]
Actually, I'll revert it again. Hashtags, mentions and links should not be spellchecked (#351) and there's also the issue from #350. I should have tested it properly before merging :/

**Pull request merged**
