### PR TITLE
Fix configure.ac

### PR DESCRIPTION
**Pull request by moschlar**
Oopsie, yes, in #736, I managed to miss committing the required changes for other tests...
Sorry 'bout that.

### CODE REVIEW

**Comment by baedert** [comment]
I don't get yes/no values printed in the summary:
```
                Corebird  1.5
                  Prefix: /usr
           Vala Compiler: /usr/bin/valac    --pkg gtk+-3.0   --pkg json-glib-1.0   --pkg rest-0.7   --pkg sqlite3   --pkg libsoup-2.4   --pkg glib-2.0   --target-glib=2.44 -D GTK322                  -D VIDEO                  --pkg gstreamer-video-1.0 -D SPELLCHECK --pkg gspell-1
           valac version: Vala 0.36.3
              C Compiler: gcc -g -O2
               Debugging: no
           Video enabled: 
       Gst check enabled: 
   Spellchecking enabled: 
```

**Comment by moschlar** [comment]
I know - that's irritating, but after closely reading https://autotools.io/autoconf/arguments.html again, I think that it should be that way.

Since it would be expected that `--disable-foo` or `--enable-foo=no` lead to them same result, all further tests if `$enable_foo` should be either `test "$enable_foo" != "no"` for when the feature is enabled or `test "$enable_foo" = "no"` when the feature is disabled.
This way, not specifying `--disable-foo` leads to `$enable_foo` being empty and matching `test "$enable_foo" != "no"`.

Before my two PRs, you couldn't specify `--enable-video` because that was handled the same way as `--disable-video` and that in turn lead to problems in the Gentoo Ebuild which always set either one of those options, depending on the set use flags.

Hope that makes it a little bit clearer.

How it would be useful to be printed in the summary, I don't know exactly...
Do you have an idea? We could of course do something like `enable_foo=${enable_foo:-yes}` somewhere...

**Comment by Vistaus** [comment]
I'm not experienced enough with autotools, but I think echo'ing might work. For example, EFL (by Enlightenment) uses that to let the user know what's disabled and what is not:
https://git.enlightenment.org/core/efl.git/tree/configure.ac
(starting at line 5812)

**Comment by moschlar** [comment]
But they use `AC_ARG_ENABLE` differently...

**Comment by baedert** [comment]
the `AC_AR_ENABLE` line for `--enable-debug` ends with `,, enable_debug=no` which specified the action-if-not-present, does that not work for the other options as well?

**Comment by Vistaus** [comment]
No trying to rush you or anything, but did you make any progress with this? 'Cause Git Master is still broken as long as #736 is not undone and this, #737, is not pulled in.

**Comment by Vistaus** [comment]
Yessss, thanks @baedert for merging this! 😄

**Pull request merged**
