### PR TITLE
Fix tweet model tests

### PR DESCRIPTION
**Pull request by IBBoard**
Tweet model tests have been failing when running "make check". This makes sure we only remove hidden tweets when there are some.

### CODE REVIEW

**Comment by baedert** [comment]
They don't fail here and I don't see a problem with passing (0, 0) as parameters to `g_ptr_array_remove_range`.

**Comment by IBBoard** [comment]
On Git Master 041f8d (plus this patch to make it GTK 3.16, so it'll build on openSUSE 42.1) I get the following:

```
../build-aux/test-driver: line 95:  4517 Trace/breakpoint trap   "$@" > $log_file 2>&1
FAIL: tweetmodel
PASS: tweetlength
PASS: utils
PASS: bundlehistory
PASS: usercounter
PASS: inlinemediadownloader
PASS: tweetparsing
PASS: filters
PASS: texttransform
PASS: avatardownload
PASS: friends
PASS: highlighting
make[4]: Entering directory '/home/ibboard/Projects/corebird/tests'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/ibboard/Projects/corebird/tests'
============================================================================
Testsuite summary for corebird 1.3
============================================================================
# TOTAL: 12
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to mail@baedert.org
============================================================================
Makefile:856: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/ibboard/Projects/corebird/tests'
Makefile:962: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/ibboard/Projects/corebird/tests'
Makefile:1112: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/ibboard/Projects/corebird/tests'
Makefile:436: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
and test-suite.log says:
```
=======================================
   corebird 1.3: tests/test-suite.log
========================================

# TOTAL: 12
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tweetmodel
================

/tweetmodel/basic-tweet-order: OK
/tweetmodel/tweet-removal: OK
/tweetmodel/clear: 
(./tweetmodel:4517): GLib-CRITICAL **: g_ptr_array_remove_range: assertion 'index_ < rarray->len' failed
```
If we're passing 0 as an index to a list of zero items, then the index won't be less than the length of the array. Yes, the library could check for that, but I thought we could also do a small change to do a sensible thing and not call a function when it won't do anything.

glib is v2.44.1

**Comment by baedert** [comment]
> (./tweetmodel:4517): GLib-CRITICAL **: g_ptr_array_remove_range: assertion 'index_ < rarray->len' failed

What? What glib version are you using here? the condition here is `index <= rarray->len` since march: https://bugzilla.gnome.org/show_bug.cgi?id=763339

**Comment by IBBoard** [comment]
My glib is 2.44.1 (I already thought of version numbers and included it at the end of the previous post 😊).

From a quick look at Git repo, it's the [latest tagged release in that branch](https://git.gnome.org/browse/glib/log/?h=glib-2-44) and was made back in May 2015. It doesn't look like the glib developers back-ported that fix to the 2.44 branch.

**Comment by baedert** [comment]
Since we depend on gtk+ 3.20 now, this is obsolete since glib 2.46 is required anyway.

**Pull request closed without merging**
