### PR TITLE
Add sound support for notifications #565

### PR DESCRIPTION
**Pull request by kajzersoze**
Optionally user can disable sounds in settings.

### CODE REVIEW

**Comment by Vistaus** [comment]
At first I thought I'd love this feature, but I already hear a sound when I get a notification. Not sure if that's only in GNOME Shell though as that's what I'm using but still. It's a vague sound but it's there.

**Comment by kajzersoze** [comment]
While there might be sound in GNOME and KDE , there isn't under other desktops.
It's better to support every DE than just a few.
And if there's already a sound support, option to disable this one is available.
Anyway, there is a demand for it, I needed it as well, so I thought why not making a PR for this issue since I already did it for myself. Merged or not I'm fine either way.

**Comment by Vistaus** [comment]
GNOME and KDE have a system-wide way of disabling sound for a specific applications. But you're right that other DE's might not have support for sound notifications so I support this pull request :-)

**Comment by Vistaus** [comment]
Btw, I noticed just now that you can already enable or disable sound for notifications in the settings:

screenshot from 2016-08-07 14-23-58

**Comment by kajzersoze** [comment]
What do you mean by "already" ? 
Without this commit there's no that option.

**Comment by Vistaus** [comment]
Then please explain how I got that option without your commit?

**Comment by kajzersoze** [comment]
That is a mystery to me :)

**Comment by kajzersoze** [comment]
btw I just realized one small problem with this by looking at your screenshot, sound will not play if "On New Tweets" is set to "Never", in all other cases it will. Easy fix, but clearly author of this app is not interested at all in this issue, so I'm just gonna close this PR

**Pull request closed without merging**
