### PR TITLE
L10n updates

### PR DESCRIPTION
**Pull request by piotrdrag**
General clean-up, some quite important.

### CODE REVIEW

**Comment by baedert** [comment]
Since I remember using the transifex client to download the translations last time, will the changes (specifically those  to the .po files of course) be overriden again next time I do that, so I shouldn't to it?
Did you use some tool to find all those problems?
Anyway, thanks a lot!

**Comment by piotrdrag** [comment]
> Since I remember using the transifex client to download the translations last time, will the changes (specifically those to the .po files of course) be overriden again next time I do that, so I shouldn't to it?

I don't know. I've never used Transifex from the developer side. You might need to make some changes to teams and languages in Transifex to match git.

> Did you use some tool to find all those problems?

Most of this was done manually. I used intltool-update -m with a patch from https://bugs.launchpad.net/intltool/+bug/1325597 to update POTFILES.

**Comment by piotrdrag** [comment]
I could split this PR into two: one with commits that should merge just fine, and one with the possibly problematic commits, if that helps.

**Comment by baedert** [comment]
Ah no, I think that's fine. Thanks!

**Pull request merged**
